#include "style_helper.h"

QString StyleHelper::loginScreen()
{
    return "QWidget#loginWindow {"
           "background-color:#F5F6F8;"
           "}"
           "QFrame#loginBrandPanel {"
           "background-color:#B91C3A;"
           "border:none;"
           "border-radius:16px;"
           "}"
           "QLabel#brandEyebrow {"
           "color:rgba(255,255,255,0.78);"
           "font-size:9pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#brandTitle {"
           "color:#FFFFFF;"
           "font-size:27pt;"
           "font-weight:700;"
           "background:transparent;"
           "}"
           "QLabel#brandSubtitle {"
           "color:rgba(255,255,255,0.9);"
           "font-size:12pt;"
           "background:transparent;"
           "}"
           "QLabel#brandFooter {"
           "color:rgba(255,255,255,0.84);"
           "font-size:10pt;"
           "background:transparent;"
           "border-top:1px solid rgba(255,255,255,0.28);"
           "padding-top:14px;"
           "}"
           "QFrame#loginCard {"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:16px;"
           "}"
           "QLabel#loginHeading {"
           "color:#24262B;"
           "font-size:20pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#loginSubheading {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QLabel#accountLabel,"
           "QLabel#passwordLabel {"
           "color:#24262B;"
           "font-size:10pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLineEdit#accountEdit,"
           "QLineEdit#passwordEdit {"
           "color:#24262B;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:8px;"
           "padding:10px 12px;"
           "font-size:11pt;"
           "selection-background-color:#B91C3A;"
           "selection-color:#FFFFFF;"
           "}"
           "QLineEdit#accountEdit:hover,"
           "QLineEdit#passwordEdit:hover {"
           "border-color:#C8CED7;"
           "}"
           "QLineEdit#accountEdit:focus,"
           "QLineEdit#passwordEdit:focus {"
           "border:1px solid #B91C3A;"
           "}"
           "QPushButton#loginButton {"
           "color:#FFFFFF;"
           "background-color:#B91C3A;"
           "border:none;"
           "border-radius:8px;"
           "padding:10px 18px;"
           "font-size:11pt;"
           "font-weight:600;"
           "}"
           "QPushButton#loginButton:hover {"
           "background-color:#991B32;"
           "}"
           "QPushButton#loginButton:pressed {"
           "background-color:#7F182C;"
           "}"
           "QLabel#loginHint {"
           "color:#68717D;"
           "font-size:9pt;"
           "background:transparent;"
           "}"
           "QLabel#loginMessage {"
           "color:#B91C3A;"
           "font-size:9pt;"
           "background:transparent;"
           "}";
}

QString StyleHelper::pageBackground()
{
    return "QWidget {"
           "background-color:#F7F7F7;"
           "}";
}

QString StyleHelper::card()
{
    return "QFrame {"
           "background-color:white;"
           "border:1px solid #EAEAEA;"
           "border-radius:16px;"
           "}";
}

QString StyleHelper::primaryButton()
{
    return "QPushButton {"
           "background-color:#B91C3A;"
           "color:white;"
           "border:none;"
           "border-radius:10px;"
           "font-weight:bold;"
           "padding:8px 18px;"
           "}"
           "QPushButton:hover {"
           "background-color:#991B32;"
           "}";
}

QString StyleHelper::secondaryButton()
{
    return "QPushButton {"
           "background-color:white;"
           "color:#555555;"
           "border:1px solid #DDDDDD;"
           "border-radius:10px;"
           "padding:8px 18px;"
           "}"
           "QPushButton:hover {"
           "background-color:#F5F5F5;"
           "}";
}

QString StyleHelper::input()
{
    return "QLineEdit,"
           "QTextEdit,"
           "QComboBox {"
           "background:white;"
           "border:1px solid #DDDDDD;"
           "border-radius:10px;"
           "padding:8px 12px;"
           "font-size:14px;"
           "}"
           "QLineEdit:focus,"
           "QTextEdit:focus,"
           "QComboBox:focus {"
           "border:1px solid #B91C3A;"
           "}";
}

QString StyleHelper::table()
{
    return "QTableWidget {"
           "background:white;"
           "border:1px solid #EAEAEA;"
           "border-radius:12px;"
           "gridline-color:#EEEEEE;"
           "}"
           "QTableWidget::item {"
           "padding:7px;"
           "}"
           "QTableWidget::item:selected {"
           "background-color:#FFF1F3;"
           "color:#333333;"
           "}"
           "QHeaderView::section {"
           "background:#FAFAFA;"
           "border:none;"
           "border-bottom:1px solid #EEEEEE;"
           "padding:8px;"
           "font-weight:bold;"
           "}";
}

QString StyleHelper::navigation()
{
    return "QListWidget {"
           "background:white;"
           "border:1px solid #EAEAEA;"
           "border-radius:14px;"
           "padding:8px;"
           "outline:none;"
           "}"
           "QListWidget::item {"
           "height:44px;"
           "padding-left:12px;"
           "border-radius:9px;"
           "margin:2px;"
           "}"
           "QListWidget::item:selected {"
           "background-color:#FFF1F3;"
           "color:#B91C3A;"
           "font-weight:bold;"
           "}"
           "QListWidget::item:hover {"
           "background-color:#F7F7F7;"
           "}";
}

QString StyleHelper::title()
{
    return "QLabel {"
           "color:#222222;"
           "font-size:20px;"
           "font-weight:bold;"
           "background:transparent;"
           "}";
}

QString StyleHelper::subtitle()
{
    return "QLabel {"
           "color:#888888;"
           "font-size:14px;"
           "background:transparent;"
           "}";
}

QString StyleHelper::studentDashboard()
{
    return "QWidget#studentDashboard {"
           "background-color:#F5F6F8;"
           "color:#24262B;"
           "}"
           "QScrollArea#dashboardScrollArea,"
           "QWidget#dashboardContent {"
           "background:transparent;"
           "border:none;"
           "}"
           "QLabel#dashboardGreeting {"
           "color:#24262B;"
           "font-size:20pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#dashboardDescription {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QFrame#dashboardStatCard,"
           "QFrame#dashboardSection,"
           "QFrame[kind=\"dashboardBadgeCard\"] {"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:12px;"
           "}"
           "QLabel#dashboardStatCaption {"
           "color:#68717D;"
           "font-size:9pt;"
           "background:transparent;"
           "}"
           "QLabel#dashboardScoreValue,"
           "QLabel#dashboardRankValue,"
           "QLabel#dashboardApprovedRecordsValue {"
           "color:#24262B;"
           "font-size:21pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#dashboardSectionTitle {"
           "color:#24262B;"
           "font-size:12pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QPushButton#dashboardActionButton {"
           "color:#24262B;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:8px;"
           "padding:8px 14px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#dashboardActionButton:hover {"
           "background-color:#F8F9FB;"
           "border-color:#C8CED7;"
           "}"
           "QPushButton#dashboardPrimaryActionButton {"
           "color:#FFFFFF;"
           "background-color:#B91C3A;"
           "border:none;"
           "border-radius:8px;"
           "padding:8px 14px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#dashboardPrimaryActionButton:hover {"
           "background-color:#991B32;"
           "}"
           "QPushButton#dashboardPrimaryActionButton:pressed {"
           "background-color:#7F182C;"
           "}"
           "QLabel#dashboardEmptyBadges {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "padding:16px 8px;"
           "}"
           "QLabel#dashboardBadgeText_C01,"
           "QLabel#dashboardBadgeText_C02,"
           "QLabel#dashboardBadgeText_C03 {"
           "color:#24262B;"
           "font-size:9pt;"
           "font-weight:600;"
           "background:transparent;"
           "}";
}

QString StyleHelper::administratorDashboard()
{
    return "QWidget#administratorDashboard {"
           "background-color:#F5F6F8;"
           "color:#24262B;"
           "}"
           "QLabel#adminDashboardTitle {"
           "color:#24262B;"
           "font-size:20pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#adminDashboardSubtitle {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QLabel#adminDashboardIdentity {"
           "color:#68717D;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:8px;"
           "padding:8px 12px;"
           "font-size:9pt;"
           "}"
           "QFrame#adminDashboardStatCard,"
           "QFrame#adminDashboardQuickSection {"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:12px;"
           "}"
           "QLabel#adminDashboardStatCaption {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QLabel#adminDashboardStatValue {"
           "color:#24262B;"
           "font-size:24pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#adminDashboardSectionTitle {"
           "color:#24262B;"
           "font-size:13pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#adminDashboardSectionSubtitle {"
           "color:#68717D;"
           "font-size:9pt;"
           "background:transparent;"
           "}"
           "QPushButton#adminDashboardAction {"
           "color:#24262B;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:8px;"
           "padding:8px 12px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#adminDashboardAction:hover {"
           "background-color:#F8F9FB;"
           "border-color:#C8CED7;"
           "}"
           "QPushButton#adminDashboardPrimaryAction {"
           "color:#FFFFFF;"
           "background-color:#B91C3A;"
           "border:none;"
           "border-radius:8px;"
           "padding:8px 12px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#adminDashboardPrimaryAction:hover {"
           "background-color:#991B32;"
           "}"
           "QPushButton#adminDashboardPrimaryAction:pressed {"
           "background-color:#7F182C;"
           "}";
}

QString StyleHelper::administratorReviewPage()
{
    return "QWidget#administratorReviewPage {"
           "background-color:#F5F6F8;"
           "color:#24262B;"
           "}"
           "QScrollArea#adminReviewScroll {"
           "background:transparent;"
           "border:none;"
           "}"
           "QScrollArea#adminReviewScroll QWidget#qt_scrollarea_viewport {"
           "background-color:#F5F6F8;"
           "border:none;"
           "}"
           "QWidget#adminReviewContent {"
           "background:transparent;"
           "}"
           "QLabel#adminReviewTitle {"
           "color:#24262B;"
           "font-size:20pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#adminReviewSubtitle {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QFrame#adminReviewFilterCard,"
           "QFrame#adminReviewTableCard,"
           "QFrame#adminReviewDetailCard {"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:12px;"
           "}"
           "QLabel#adminReviewSectionTitle {"
           "color:#24262B;"
           "font-size:13pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#adminReviewFieldLabel {"
           "color:#68717D;"
           "font-size:10pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#adminReviewField {"
           "color:#24262B;"
           "font-size:10pt;"
           "background:transparent;"
           "padding:2px 0;"
           "}"
           "QLabel#adminReviewDetailStatus[reviewStatus=\"pending\"] {"
           "color:#B7791F;"
           "font-weight:600;"
           "}"
           "QLabel#adminReviewDetailStatus[reviewStatus=\"approved\"] {"
           "color:#2F855A;"
           "font-weight:600;"
           "}"
           "QLabel#adminReviewDetailStatus[reviewStatus=\"rejected\"] {"
           "color:#C2413A;"
           "font-weight:600;"
           "}"
           "QComboBox#adminReviewStatusFilter {"
           "color:#24262B;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:8px;"
           "padding:7px 10px;"
           "font-size:10pt;"
           "}"
           "QComboBox#adminReviewStatusFilter:hover {"
           "border-color:#C8CED7;"
           "}"
           "QComboBox#adminReviewStatusFilter:focus {"
           "border:1px solid #B91C3A;"
           "}"
           "QPushButton#adminReviewRefreshButton {"
           "color:#24262B;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:8px;"
           "padding:8px 14px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#adminReviewRefreshButton:hover {"
           "background-color:#F8F9FB;"
           "border-color:#C8CED7;"
           "}"
           "QPushButton#adminReviewRefreshButton:pressed {"
           "background-color:#F0F2F5;"
           "}"
           "QTableWidget#adminReviewTable {"
           "background-color:#FFFFFF;"
           "alternate-background-color:#FAFBFC;"
           "color:#24262B;"
           "border:none;"
           "gridline-color:#E4E7EC;"
           "selection-background-color:#FCEAED;"
           "selection-color:#24262B;"
           "font-size:10pt;"
           "}"
           "QTableWidget#adminReviewTable::item {"
           "padding:9px 10px;"
           "border-bottom:1px solid #F0F1F3;"
           "}"
           "QTableWidget#adminReviewTable::item:selected {"
           "background-color:#FCEAED;"
           "border:none;"
           "border-radius:0px;"
           "}"
           "QTableWidget#adminReviewTable::item:focus {"
           "border:none;"
           "border-radius:0px;"
           "outline:none;"
           "}"
           "QTableWidget#adminReviewTable::item:selected:focus {"
           "background-color:#FCEAED;"
           "border:none;"
           "border-radius:0px;"
           "outline:none;"
           "}"
           "QTableWidget#adminReviewTable QHeaderView::section {"
           "color:#68717D;"
           "background-color:#F7F8FA;"
           "border:none;"
           "border-bottom:1px solid #E4E7EC;"
           "padding:10px 8px;"
           "font-size:9pt;"
           "font-weight:600;"
           "}"
           "QLabel#adminReviewEmptyState {"
           "color:#68717D;"
           "background-color:#FAFBFC;"
           "border:1px dashed #E4E7EC;"
           "border-radius:8px;"
           "padding:20px;"
           "font-size:10pt;"
           "}"
           "QPushButton#adminReviewApproveButton {"
           "color:#FFFFFF;"
           "background-color:#2F855A;"
           "border:none;"
           "border-radius:8px;"
           "padding:9px 16px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#adminReviewApproveButton:hover {"
           "background-color:#276749;"
           "}"
           "QPushButton#adminReviewApproveButton:pressed {"
           "background-color:#1F5D42;"
           "}"
           "QPushButton#adminReviewRejectButton {"
           "color:#C2413A;"
           "background-color:#FFFFFF;"
           "border:1px solid #EBC7C4;"
           "border-radius:8px;"
           "padding:9px 16px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#adminReviewRejectButton:hover {"
           "background-color:#FDF2F1;"
           "border-color:#C2413A;"
           "}"
           "QPushButton#adminReviewRejectButton:pressed {"
           "background-color:#F9E5E3;"
           "}";
}

QString StyleHelper::studentRecordsPage()
{
    return "QWidget#studentRecordsPage {"
           "background-color:#F5F6F8;"
           "color:#24262B;"
           "}"
           "QLabel#studentRecordsTitle {"
           "color:#24262B;"
           "font-size:20pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#studentRecordsSubtitle {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QFrame#studentRecordsFilterCard,"
           "QFrame#studentRecordsTableCard {"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:12px;"
           "}"
           "QLabel#studentRecordsSectionTitle {"
           "color:#24262B;"
           "font-size:13pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#studentRecordsFieldLabel {"
           "color:#68717D;"
           "font-size:9pt;"
           "background:transparent;"
           "}"
           "QComboBox#studentRecordsCategoryFilter,"
           "QDateEdit#studentRecordsStartDate,"
           "QDateEdit#studentRecordsEndDate {"
           "color:#24262B;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:8px;"
           "padding:7px 9px;"
           "font-size:10pt;"
           "}"
           "QComboBox#studentRecordsCategoryFilter:focus,"
           "QDateEdit#studentRecordsStartDate:focus,"
           "QDateEdit#studentRecordsEndDate:focus {"
           "border:1px solid #B91C3A;"
           "}"
           "QPushButton#studentRecordsRefreshButton,"
           "QPushButton#studentRecordsClearButton,"
           "QPushButton#studentRecordsModifyButton {"
           "color:#24262B;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:8px;"
           "padding:8px 12px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#studentRecordsRefreshButton:hover,"
           "QPushButton#studentRecordsClearButton:hover,"
           "QPushButton#studentRecordsModifyButton:hover {"
           "background-color:#F8F9FB;"
           "border-color:#C8CED7;"
           "}"
           "QPushButton#studentRecordsSearchButton {"
           "color:#FFFFFF;"
           "background-color:#B91C3A;"
           "border:none;"
           "border-radius:8px;"
           "padding:8px 14px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#studentRecordsSearchButton:hover {"
           "background-color:#991B32;"
           "}"
           "QPushButton#studentRecordsDeleteButton {"
           "color:#C2413A;"
           "background-color:#FFFFFF;"
           "border:1px solid #EBC7C4;"
           "border-radius:8px;"
           "padding:8px 12px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#studentRecordsDeleteButton:hover {"
           "background-color:#FDF2F1;"
           "border-color:#C2413A;"
           "}"
           "QTableWidget#studentRecordsTable {"
           "background-color:#FFFFFF;"
           "alternate-background-color:#FAFBFC;"
           "color:#24262B;"
           "border:none;"
           "gridline-color:#E4E7EC;"
           "selection-background-color:#FCEAED;"
           "selection-color:#24262B;"
           "font-size:10pt;"
           "}"
           "QTableWidget#studentRecordsTable::item {"
           "padding:8px 10px;"
           "border-bottom:1px solid #F0F1F3;"
           "}"
           "QTableWidget#studentRecordsTable::item:selected {"
           "background-color:#FCEAED;"
           "border:none;"
           "border-radius:0px;"
           "}"
           "QTableWidget#studentRecordsTable::item:focus {"
           "border:none;"
           "border-radius:0px;"
           "outline:none;"
           "}"
           "QTableWidget#studentRecordsTable::item:selected:focus {"
           "background-color:#FCEAED;"
           "border:none;"
           "border-radius:0px;"
           "outline:none;"
           "}"
           "QHeaderView::section {"
           "color:#68717D;"
           "background-color:#F7F8FA;"
           "border:none;"
           "border-bottom:1px solid #E4E7EC;"
           "padding:10px 8px;"
           "font-size:9pt;"
           "font-weight:600;"
           "}"
           "QLabel#studentRecordsEmptyState {"
           "color:#68717D;"
           "background-color:#FAFBFC;"
           "border:1px dashed #E4E7EC;"
           "border-radius:8px;"
           "padding:20px;"
           "font-size:10pt;"
           "}"
           "QPushButton#studentRecordsRefreshButton:pressed,"
           "QPushButton#studentRecordsClearButton:pressed,"
           "QPushButton#studentRecordsModifyButton:pressed {"
           "background-color:#F0F2F5;"
           "}"
           "QPushButton#studentRecordsSearchButton:pressed {"
           "background-color:#7F182C;"
           "}"
           "QPushButton#studentRecordsDeleteButton:pressed {"
           "background-color:#F9E5E3;"
           "}";
}

QString StyleHelper::studentRecordsCalendarPopup()
{
    return "QWidget#qt_calendar_navigationbar {"
           "background-color:#F5F6F8;"
           "}"
           "QToolButton#qt_calendar_monthbutton,"
           "QToolButton#qt_calendar_yearbutton {"
           "color:#24262B;"
           "background-color:transparent;"
           "border:1px solid transparent;"
           "border-radius:6px;"
           "padding:4px 8px;"
           "font-weight:600;"
           "}"
           "QToolButton#qt_calendar_monthbutton:hover,"
           "QToolButton#qt_calendar_yearbutton:hover {"
           "background-color:#FCEAED;"
           "}"
           "QToolButton#qt_calendar_monthbutton:pressed,"
           "QToolButton#qt_calendar_yearbutton:pressed {"
           "background-color:#F8DDE2;"
           "}"
           "QToolButton#qt_calendar_prevmonth,"
           "QToolButton#qt_calendar_nextmonth {"
           "color:#68717D;"
           "background-color:transparent;"
           "border:1px solid transparent;"
           "border-radius:6px;"
           "}"
           "QToolButton#qt_calendar_prevmonth:hover,"
           "QToolButton#qt_calendar_nextmonth:hover {"
           "background-color:#EDEFF2;"
           "}"
           "QToolButton#qt_calendar_prevmonth:pressed,"
           "QToolButton#qt_calendar_nextmonth:pressed {"
           "background-color:#E4E7EC;"
           "}"
           "QSpinBox#qt_calendar_yearedit {"
           "color:#24262B;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:4px;"
           "}"
           "QSpinBox#qt_calendar_yearedit QLineEdit {"
           "color:#24262B;"
           "background-color:#FFFFFF;"
           "border:none;"
           "selection-background-color:#B91C3A;"
           "selection-color:#FFFFFF;"
           "}";
}

QString StyleHelper::studentAchievementPage()
{
    return "QWidget#studentAchievementPage {"
           "background-color:#F5F6F8;"
           "color:#24262B;"
           "}"
           "QScrollArea#achievementScrollArea,"
           "QWidget#achievementContent {"
           "background:transparent;"
           "border:none;"
           "}"
           "QLabel#achievementTitle {"
           "color:#24262B;"
           "font-size:20pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#achievementSubtitle {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QFrame#achievementCategoryCard {"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:12px;"
           "}"
           "QLabel#achievementCategoryTitle {"
           "color:#24262B;"
           "font-size:13pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#achievementDuration_C01,"
           "QLabel#achievementDuration_C02,"
           "QLabel#achievementDuration_C03 {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QLabel#achievementCurrentLevel_C01,"
           "QLabel#achievementCurrentLevel_C02,"
           "QLabel#achievementCurrentLevel_C03 {"
           "color:#24262B;"
           "font-size:10pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QProgressBar#achievementProgress_C01,"
           "QProgressBar#achievementProgress_C02,"
           "QProgressBar#achievementProgress_C03 {"
           "background-color:#F1F2F4;"
           "border:none;"
           "border-radius:4px;"
           "min-height:8px;"
           "max-height:8px;"
           "}"
           "QProgressBar#achievementProgress_C01::chunk,"
           "QProgressBar#achievementProgress_C02::chunk,"
           "QProgressBar#achievementProgress_C03::chunk {"
           "background-color:#C58A24;"
           "border-radius:4px;"
           "}"
           "QLabel#achievementNextGoal_C01,"
           "QLabel#achievementNextGoal_C02,"
           "QLabel#achievementNextGoal_C03 {"
           "color:#68717D;"
           "font-size:9pt;"
           "background:transparent;"
           "}"
           "QFrame#achievementBadgeTile {"
           "background-color:#F8F9FB;"
           "border:1px solid #E4E7EC;"
           "border-radius:10px;"
           "}"
           "QLabel#achievementBadgeIcon_C01_1,"
           "QLabel#achievementBadgeIcon_C01_2,"
           "QLabel#achievementBadgeIcon_C01_3,"
           "QLabel#achievementBadgeIcon_C02_1,"
           "QLabel#achievementBadgeIcon_C02_2,"
           "QLabel#achievementBadgeIcon_C02_3,"
           "QLabel#achievementBadgeIcon_C03_1,"
           "QLabel#achievementBadgeIcon_C03_2,"
           "QLabel#achievementBadgeIcon_C03_3 {"
           "background:transparent;"
           "}"
           "QLabel#achievementBadgeLevel {"
           "color:#24262B;"
           "font-size:9pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel[earned=\"true\"] {"
           "color:#B91C3A;"
           "font-size:9pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel[earned=\"false\"] {"
           "color:#68717D;"
           "font-size:9pt;"
           "background:transparent;"
           "}"
           "QPushButton#achievementRefreshButton {"
           "color:#FFFFFF;"
           "background-color:#B91C3A;"
           "border:none;"
           "border-radius:8px;"
           "padding:8px 14px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#achievementRefreshButton:hover {"
           "background-color:#991B32;"
           "}"
           "QPushButton#achievementRefreshButton:pressed {"
           "background-color:#7F182C;"
           "}";
}

QString StyleHelper::studentRankingPage()
{
    return "QWidget#studentRankingPage {"
           "background-color:#F5F6F8;"
           "color:#24262B;"
           "}"
           "QScrollArea#rankingScrollArea,"
           "QWidget#rankingContent {"
           "background:transparent;"
           "border:none;"
           "}"
           "QScrollArea#rankingScrollArea QWidget#qt_scrollarea_viewport {"
           "background-color:#F5F6F8;"
           "border:none;"
           "}"
           "QLabel#rankingTitle {"
           "color:#24262B;"
           "font-size:20pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#rankingSubtitle {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QFrame#rankingTopSection,"
           "QFrame#rankingTableCard {"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:12px;"
           "}"
           "QLabel#rankingSectionTitle,"
           "QLabel#rankingTableTitle {"
           "color:#24262B;"
           "font-size:13pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#rankingSectionCaption {"
           "color:#68717D;"
           "font-size:9pt;"
           "background:transparent;"
           "}"
           "QFrame#rankingTopCard {"
           "background-color:#FFFFFF;"
           "border:2px solid #B91C3A;"
           "border-radius:10px;"
           "}"
           "QFrame#rankingTopCard[rankBand=\"first\"] {"
           "border:2px solid #B91C3A;"
           "}"
           "QFrame#rankingTopCard[rankBand=\"second\"] {"
           "border:2px solid #A7AFBA;"
           "}"
           "QFrame#rankingTopCard[rankBand=\"third\"] {"
           "border:2px solid #B87945;"
           "}"
           "QFrame#rankingTopCard[currentStudent=\"true\"] {"
           "background-color:#FFF7F8;"
           "}"
           "QLabel#rankingTopRank {"
           "color:#B91C3A;"
           "font-size:11pt;"
           "font-weight:700;"
           "background:transparent;"
           "}"
           "QLabel#rankingStarText {"
           "color:#8F6517;"
           "font-size:9pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#rankingTopStudent {"
           "color:#24262B;"
           "font-size:12pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#rankingTopAccount {"
           "color:#68717D;"
           "font-size:9pt;"
           "background:transparent;"
           "}"
           "QLabel#rankingTopScore {"
           "color:#24262B;"
           "font-size:11pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QTableWidget#rankingTable {"
           "background-color:#FFFFFF;"
           "alternate-background-color:#FAFBFC;"
           "color:#24262B;"
           "border:none;"
           "gridline-color:#E4E7EC;"
           "selection-background-color:#FCEAED;"
           "selection-color:#24262B;"
           "font-size:10pt;"
           "}"
           "QTableWidget#rankingTable::item {"
           "padding:8px 10px;"
           "border-bottom:1px solid #F0F1F3;"
           "}"
           "QTableWidget#rankingTable::item:selected {"
           "background-color:#FCEAED;"
           "color:#24262B;"
           "border:none;"
           "}"
           "QTableWidget#rankingTable QHeaderView::section {"
           "color:#68717D;"
           "background-color:#F7F8FA;"
           "border:none;"
           "border-bottom:1px solid #E4E7EC;"
           "padding:10px 8px;"
           "font-size:9pt;"
           "font-weight:600;"
           "}"
           "QWidget#rankingSpecialtyBadgeStrip {"
           "background:transparent;"
           "}"
           "QWidget#rankingSpecialtyBadgeStrip[currentStudent=\"true\"] {"
           "background-color:#FCEAED;"
           "}"
           "QLabel#rankingSpecialtyBadge {"
           "background:transparent;"
           "}"
           "QLabel#rankingNoBadgeState {"
           "color:#68717D;"
           "background:transparent;"
           "border:none;"
           "border-radius:0px;"
           "padding:0px;"
           "font-size:9pt;"
           "}"
           "QLabel#rankingEmptyState {"
           "color:#68717D;"
           "background-color:#FAFBFC;"
           "border:1px dashed #E4E7EC;"
           "border-radius:8px;"
           "padding:12px;"
           "font-size:9pt;"
           "}"
           "QPushButton#rankingRefreshButton {"
           "color:#FFFFFF;"
           "background-color:#B91C3A;"
           "border:none;"
           "border-radius:8px;"
           "padding:8px 14px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#rankingRefreshButton:hover {"
           "background-color:#991B32;"
           "}"
           "QPushButton#rankingRefreshButton:pressed {"
           "background-color:#7F182C;"
           "}";
}

QString StyleHelper::studentDiaryPages()
{
    return "QWidget#studentDiaryPage,"
           "QWidget#studentDiaryWallPage {"
           "background-color:#F5F6F8;"
           "color:#24262B;"
           "}"
           "QScrollArea#studentDiaryScrollArea,"
           "QWidget#studentDiaryFeedContainer {"
           "background:transparent;"
           "border:none;"
           "}"
           "QLabel#studentDiaryPageTitle {"
           "color:#24262B;"
           "font-size:20pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#studentDiaryPageSubtitle {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QFrame#studentDiaryPublishCard,"
           "QFrame#studentDiaryPostCard {"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:14px;"
           "}"
           "QLabel#studentDiaryCardTitle {"
           "color:#24262B;"
           "font-size:12pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#studentDiaryFieldLabel {"
           "color:#4B5563;"
           "font-size:10pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QComboBox#studentDiaryRecordSelector,"
           "QTextEdit#studentDiaryMessageEditor {"
           "color:#24262B;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:8px;"
           "padding:9px 11px;"
           "font-size:10pt;"
           "}"
           "QComboBox#studentDiaryRecordSelector:hover,"
           "QTextEdit#studentDiaryMessageEditor:hover {"
           "border-color:#C8CED7;"
           "}"
           "QComboBox#studentDiaryRecordSelector:focus,"
           "QTextEdit#studentDiaryMessageEditor:focus {"
           "border:1px solid #B91C3A;"
           "}"
           "QComboBox#studentDiaryRecordSelector::drop-down {"
           "border:none;"
           "width:28px;"
           "}"
           "QPushButton#studentDiaryPrimaryButton {"
           "color:#FFFFFF;"
           "background-color:#B91C3A;"
           "border:none;"
           "border-radius:8px;"
           "padding:9px 18px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#studentDiaryPrimaryButton:hover {"
           "background-color:#991B32;"
           "}"
           "QPushButton#studentDiaryPrimaryButton:pressed {"
           "background-color:#7F182C;"
           "}"
           "QPushButton#studentDiarySecondaryButton {"
           "color:#B91C3A;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:8px;"
           "padding:8px 15px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#studentDiarySecondaryButton:hover {"
           "background-color:#FFF7F8;"
           "border-color:#E7B4BE;"
           "}"
           "QLabel#studentDiaryAvatar {"
           "color:#B91C3A;"
           "background-color:#FCEAED;"
           "border-radius:19px;"
           "font-weight:700;"
           "}"
           "QLabel#studentDiaryAuthorName {"
           "color:#24262B;"
           "font-size:10pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#studentDiaryAuthorId,"
           "QLabel#studentDiaryFact {"
           "color:#68717D;"
           "font-size:9pt;"
           "background:transparent;"
           "}"
           "QLabel#studentDiaryMessage {"
           "color:#24262B;"
           "font-size:12pt;"
           "background:transparent;"
           "padding-top:6px;"
           "padding-bottom:6px;"
           "}"
           "QPushButton#studentDiaryLikeButton {"
           "color:#68717D;"
           "background:transparent;"
           "border:none;"
           "border-radius:17px;"
           "font-size:19pt;"
           "font-weight:600;"
           "}"
           "QPushButton#studentDiaryLikeButton:hover {"
           "color:#B91C3A;"
           "background-color:#FFF1F3;"
           "}"
           "QPushButton#studentDiaryLikeButton[liked=\"true\"] {"
           "color:#B91C3A;"
           "}"
           "QLabel#studentDiaryLikeCount {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QLabel#studentDiaryLikeCount[liked=\"true\"] {"
           "color:#B91C3A;"
           "font-weight:600;"
           "}"
           "QLabel#studentDiaryEmptyState {"
           "color:#68717D;"
           "background-color:#FFFFFF;"
           "border:1px dashed #D7DCE3;"
           "border-radius:14px;"
           "padding:28px;"
           "font-size:11pt;"
           "}";
}

QString StyleHelper::profilePages()
{
    return "QWidget#studentProfilePage,"
           "QWidget#administratorProfilePage {"
           "background-color:#F5F6F8;"
           "color:#24262B;"
           "}"
           "QLabel#profilePageTitle {"
           "color:#24262B;"
           "font-size:20pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#profilePageSubtitle {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QFrame#profileIdentityCard,"
           "QFrame#profileInfoCard,"
           "QFrame#profileSecurityCard {"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:12px;"
           "}"
           "QLabel#profileIdentityAvatar {"
           "color:#B91C3A;"
           "background-color:#FCEAED;"
           "border-radius:32px;"
           "font-size:24pt;"
           "font-weight:600;"
           "}"
           "QLabel#profileIdentityName {"
           "color:#24262B;"
           "font-size:16pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#profileIdentityAccount {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QLabel#profileSectionTitle {"
           "color:#24262B;"
           "font-size:12pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#profileFieldLabel {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QLabel#profileFieldValue,"
           "QLabel#profileAccountDetail,"
           "QLabel#profileNameDetail,"
           "QLabel#adminAccountDetail,"
           "QLabel#adminNameDetail {"
           "color:#24262B;"
           "font-size:10pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#profileSecurityDescription {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QPushButton#profilePasswordButton {"
           "color:#FFFFFF;"
           "background-color:#B91C3A;"
           "border:none;"
           "border-radius:8px;"
           "padding:9px 18px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#profilePasswordButton:hover {"
           "background-color:#991B32;"
           "}"
           "QPushButton#profilePasswordButton:pressed {"
           "background-color:#7F182C;"
           "}";
}
