#include "style_helper.h"

QString StyleHelper::loginScreen()
{
    return "QWidget#loginWindow {"
           "background-color:#F5F6F8;"
           "}"
           "QFrame#loginBrandPanel {"
           "background-color:#B91C3A;"
           "border:none;"
           "border-radius:16px;"
           "}"
           "QLabel#brandEyebrow {"
           "color:rgba(255,255,255,0.78);"
           "font-size:9pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#brandTitle {"
           "color:#FFFFFF;"
           "font-size:27pt;"
           "font-weight:700;"
           "background:transparent;"
           "}"
           "QLabel#brandSubtitle {"
           "color:rgba(255,255,255,0.9);"
           "font-size:12pt;"
           "background:transparent;"
           "}"
           "QLabel#brandFooter {"
           "color:rgba(255,255,255,0.84);"
           "font-size:10pt;"
           "background:transparent;"
           "border-top:1px solid rgba(255,255,255,0.28);"
           "padding-top:14px;"
           "}"
           "QFrame#loginCard {"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:16px;"
           "}"
           "QLabel#loginHeading {"
           "color:#24262B;"
           "font-size:20pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#loginSubheading {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QLabel#accountLabel,"
           "QLabel#passwordLabel {"
           "color:#24262B;"
           "font-size:10pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLineEdit#accountEdit,"
           "QLineEdit#passwordEdit {"
           "color:#24262B;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:8px;"
           "padding:10px 12px;"
           "font-size:11pt;"
           "selection-background-color:#B91C3A;"
           "selection-color:#FFFFFF;"
           "}"
           "QLineEdit#accountEdit:hover,"
           "QLineEdit#passwordEdit:hover {"
           "border-color:#C8CED7;"
           "}"
           "QLineEdit#accountEdit:focus,"
           "QLineEdit#passwordEdit:focus {"
           "border:1px solid #B91C3A;"
           "}"
           "QPushButton#loginButton {"
           "color:#FFFFFF;"
           "background-color:#B91C3A;"
           "border:none;"
           "border-radius:8px;"
           "padding:10px 18px;"
           "font-size:11pt;"
           "font-weight:600;"
           "}"
           "QPushButton#loginButton:hover {"
           "background-color:#991B32;"
           "}"
           "QPushButton#loginButton:pressed {"
           "background-color:#7F182C;"
           "}"
           "QLabel#loginHint {"
           "color:#68717D;"
           "font-size:9pt;"
           "background:transparent;"
           "}"
           "QLabel#loginMessage {"
           "color:#B91C3A;"
           "font-size:9pt;"
           "background:transparent;"
           "}";
}

QString StyleHelper::pageBackground()
{
    return "QWidget {"
           "background-color:#F7F7F7;"
           "}";
}

QString StyleHelper::card()
{
    return "QFrame {"
           "background-color:white;"
           "border:1px solid #EAEAEA;"
           "border-radius:16px;"
           "}";
}

QString StyleHelper::primaryButton()
{
    return "QPushButton {"
           "background-color:#B91C3A;"
           "color:white;"
           "border:none;"
           "border-radius:10px;"
           "font-weight:bold;"
           "padding:8px 18px;"
           "}"
           "QPushButton:hover {"
           "background-color:#991B32;"
           "}";
}

QString StyleHelper::secondaryButton()
{
    return "QPushButton {"
           "background-color:white;"
           "color:#555555;"
           "border:1px solid #DDDDDD;"
           "border-radius:10px;"
           "padding:8px 18px;"
           "}"
           "QPushButton:hover {"
           "background-color:#F5F5F5;"
           "}";
}

QString StyleHelper::input()
{
    return "QLineEdit,"
           "QTextEdit,"
           "QComboBox {"
           "background:white;"
           "border:1px solid #DDDDDD;"
           "border-radius:10px;"
           "padding:8px 12px;"
           "font-size:14px;"
           "}"
           "QLineEdit:focus,"
           "QTextEdit:focus,"
           "QComboBox:focus {"
           "border:1px solid #B91C3A;"
           "}";
}

QString StyleHelper::table()
{
    return "QTableWidget {"
           "background:white;"
           "border:1px solid #EAEAEA;"
           "border-radius:12px;"
           "gridline-color:#EEEEEE;"
           "}"
           "QTableWidget::item {"
           "padding:7px;"
           "}"
           "QTableWidget::item:selected {"
           "background-color:#FFF1F3;"
           "color:#333333;"
           "}"
           "QHeaderView::section {"
           "background:#FAFAFA;"
           "border:none;"
           "border-bottom:1px solid #EEEEEE;"
           "padding:8px;"
           "font-weight:bold;"
           "}";
}

QString StyleHelper::navigation()
{
    return "QListWidget {"
           "background:white;"
           "border:1px solid #EAEAEA;"
           "border-radius:14px;"
           "padding:8px;"
           "outline:none;"
           "}"
           "QListWidget::item {"
           "height:44px;"
           "padding-left:12px;"
           "border-radius:9px;"
           "margin:2px;"
           "}"
           "QListWidget::item:selected {"
           "background-color:#FFF1F3;"
           "color:#B91C3A;"
           "font-weight:bold;"
           "}"
           "QListWidget::item:hover {"
           "background-color:#F7F7F7;"
           "}";
}

QString StyleHelper::title()
{
    return "QLabel {"
           "color:#222222;"
           "font-size:20px;"
           "font-weight:bold;"
           "background:transparent;"
           "}";
}

QString StyleHelper::subtitle()
{
    return "QLabel {"
           "color:#888888;"
           "font-size:14px;"
           "background:transparent;"
           "}";
}

QString StyleHelper::studentDashboard()
{
    return "QWidget#studentDashboard {"
           "background-color:#F5F6F8;"
           "color:#24262B;"
           "}"
           "QScrollArea#dashboardScrollArea,"
           "QWidget#dashboardContent {"
           "background:transparent;"
           "border:none;"
           "}"
           "QLabel#dashboardGreeting {"
           "color:#24262B;"
           "font-size:20pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#dashboardDescription {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "}"
           "QFrame#dashboardStatCard,"
           "QFrame#dashboardSection,"
           "QFrame[kind=\"dashboardBadgeCard\"] {"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:12px;"
           "}"
           "QLabel#dashboardStatCaption {"
           "color:#68717D;"
           "font-size:9pt;"
           "background:transparent;"
           "}"
           "QLabel#dashboardScoreValue,"
           "QLabel#dashboardRankValue,"
           "QLabel#dashboardApprovedRecordsValue {"
           "color:#24262B;"
           "font-size:21pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QLabel#dashboardSectionTitle {"
           "color:#24262B;"
           "font-size:12pt;"
           "font-weight:600;"
           "background:transparent;"
           "}"
           "QPushButton#dashboardActionButton {"
           "color:#24262B;"
           "background-color:#FFFFFF;"
           "border:1px solid #E4E7EC;"
           "border-radius:8px;"
           "padding:8px 14px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#dashboardActionButton:hover {"
           "background-color:#F8F9FB;"
           "border-color:#C8CED7;"
           "}"
           "QPushButton#dashboardPrimaryActionButton {"
           "color:#FFFFFF;"
           "background-color:#B91C3A;"
           "border:none;"
           "border-radius:8px;"
           "padding:8px 14px;"
           "font-size:10pt;"
           "font-weight:600;"
           "}"
           "QPushButton#dashboardPrimaryActionButton:hover {"
           "background-color:#991B32;"
           "}"
           "QPushButton#dashboardPrimaryActionButton:pressed {"
           "background-color:#7F182C;"
           "}"
           "QLabel#dashboardEmptyBadges {"
           "color:#68717D;"
           "font-size:10pt;"
           "background:transparent;"
           "padding:16px 8px;"
           "}"
           "QLabel#dashboardBadgeText_C01,"
           "QLabel#dashboardBadgeText_C02,"
           "QLabel#dashboardBadgeText_C03 {"
           "color:#24262B;"
           "font-size:9pt;"
           "font-weight:600;"
           "background:transparent;"
           "}";
}
